### ISSUE TITLE
document.referrer use?

### ISSUE THREAD

**Issue by donmccurdy** [bghgary/glTF-Assets-Viewer#9]
Wondering what the purpose is for the `document.referrer` reference here...

https://github.com/bghgary/glTF-Assets-Viewer/blob/master/index.js#L220-L227

... as opposed to just hard-coding a URL. I guess that ensures links work on a branch? Not a big deal, but I tried to copy/paste links to demos out of a readme and was surprised when they didn't work when clicked from another site. :)

**Comment by bghgary** [comment]
Branch and most importantly PRs so reviews are possible. That was the fastest way I can think of to do it with markdown. There are probably better ways. The URL should be updated after you click the link, then you can copy it.

**Comment by donmccurdy** [comment]
Ok, seems as good as anything — thanks!
